import './styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
// import { GoogleOAuthProvider } from "@react-oauth/google"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FreeStuffs',
  description: 'Generated by create next app',
}
export default function RootLayout( { children,}: {children: React.ReactNode}) {

  return (
    <html lang="en">
        <body className={inter.className}>
          {/* <GoogleOAuthProvider clientId={`${process.env.NEXT_PUBLIC_GOOGLE_API_TOKEN}`}> */}
          <div className='xl:w-[1200px] m-auto overflow-hidden h-[100vh]'>
              <Navbar />
              <div className='flex gap-3 md:gap-10 '>
                <div className='h-[92vh] overflow-hidden xl:hover:overflow-auto'>
                  <Sidebar />
                </div>
                <div className='mt-4 flex flex-col gap-10 overflow-auto h-[88vh] videos flex-1'>
                  {children}
                </div>
              </div>  
          </div>        
          {/* </GoogleOAuthProvider> */}
        </body>
    </html>
  )
}
